name: pages

on:
  push:
    branches:
      - master

jobs:
  public:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15

    - name: Install
      run: |
        npm ci
        gulp

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPOSITORY_NAME: doubleui/doubleui.github.io 
        BRANCH: master
        FOLDER: dist
        CLEAN: true
