name: pages

on:
  push:
    branches:
      - master

jobs:
  public:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15

    - name: Install
      run: |
        npm ci
        gulp

    - name: Check gulp workflow
      run: ls -la
